service: umudik-apig-serverless
provider:
  name: aws
  runtime: nodejs14.x
  region: eu-central-1
  websocketsApiRouteSelectionExpression: $request.body.action
functions:
  authorizer:
    handler: handler.auth
  connection:
    handler: handler.connection
    events:
      - websocket:
          route: $connect
          authorizer:
            name: authorizer
            identitySource:
              - 'route.request.header.X-Forwarded-Proto'
      - websocket:
          route: $disconnect
      - websocket:
          route: $default